export interface inoutManagementUploadType {
  plantCd: stringNull
  plantName: stringNull
  materialCd: stringNull
  mdmChemMaterialName: stringNull
  year: stringNull
  in1: stringNull
  in2: stringNull
  in3: stringNull
  in4: stringNull
  in5: stringNull
  in6: stringNull
  in7: stringNull
  in8: stringNull
  in9: stringNull
  in10: stringNull
  in11: stringNull
  in12: stringNull
  out1: stringNull
  out2: stringNull
  out3: stringNull
  out4: stringNull
  out5: stringNull
  out6: stringNull
  out7: stringNull
  out8: stringNull
  out9: stringNull
  out10: stringNull
  out11: stringNull
  out12: stringNull
  invetory1: stringNull
  invetory2: stringNull
  invetory3: stringNull
  invetory4: stringNull
  invetory5: stringNull
  invetory6: stringNull
  invetory7: stringNull
  invetory8: stringNull
  invetory9: stringNull
  invetory10: stringNull
  invetory11: stringNull
  invetory12: stringNull
}
