import { dataBaseType } from '@/types/dataBase'

export interface consultHistoryType extends dataBaseType {
  editFlag: stringNull
  regUserId: stringNull
  regUserName: stringNull
  regUserDeptName: stringNull
  chgUserId: stringNull
  chgUserName: stringNull
  chgUserDeptName: stringNull
  userDeptCd: stringNull
  approvalTypeCd: stringNull
  approvalStatusCd: stringNull
  approvalStatusName: stringNull
  sysApprovalRequestId: stringNull
  plantCdList: stringNull
  regDt: stringNull
  regDtStr: stringNull
  regDtStrTime: stringNull
  chgDt: stringNull
  chgDtStr: stringNull
  chgDtStrTime: stringNull
  suspectConsultId: stringNull
  suspectId: stringNull
  heaBrainCardiovascularSurveyId: stringNull
  consultContent: stringNull
  consultDate: stringNull
  diseasePast: stringNull
  diseaseCurrent: stringNull
  symptom: stringNull
  remark: stringNull
  consultTypeCd: stringNull
  consultTypeName: stringNull
  counselorName: stringNull
  glycatedHemoglobin: stringNull
  liverOt: stringNull
  liverPt: stringNull
  gripStrengthLeft: stringNull
  gripStrengthRight: stringNull
  peeCheckResult: stringNull
  ldlCholesterol: stringNull
  hdlCholesterol: stringNull
  neutralFat: stringNull
  smoking: stringNull
  drinking: stringNull
  exercise: stringNull
  bloodSugar: stringNull
  totalCholesterol: stringNull
  deptCd: stringNull
  userId: stringNull
  userInfo: stringNull
  plantCd: stringNull
  plantName: stringNull
  diastole: stringNull
  systole: stringNull
  medicineList?: stringNull
  deleteMedicineList?: stringNull
}

export interface consultHistoryDataType extends dataBaseType {
  suspectConsultId: stringNull
  suspectId: stringNull
  heaBrainCardiovascularSurveyId: stringNull
  suspectUserId: stringNull
  consultContent: stringNull
  consultDate: stringNull
  diseasePast: stringNull
  diseaseCurrent: stringNull
  symptom: stringNull
  remark: stringNull
  consultTypeCd: stringNull
  counselorName: stringNull
  glycatedHemoglobin: stringNull
  liverOt: stringNull
  liverPt: stringNull
  gripStrengthLeft: stringNull
  gripStrengthRight: stringNull
  peeCheckResult: stringNull
  ldlCholesterol: stringNull
  hdlCholesterol: stringNull
  neutralFat: stringNull
  smoking: stringNull
  drinking: stringNull
  exercise: stringNull
  bloodSugar: stringNull
  totalCholesterol: stringNull
  diastole: stringNull
  systole: stringNull
  regUserId: stringNull
  chgUserId: stringNull
  deptCd: stringNull
  userId: stringNull
  heaCheckupResultId?: stringNull
}
